### ISSUE TITLE
Fitbit Sense . No data.

### ISSUE THREAD

**Issue by Tombella** [schana/carim-clock#1]
I have a new Sense and loved your clock face. Worked fine for a day or two but now no data is displayed just the icons..

Uninstalled, installed, rebooted, no joy. Fitbit help says ask you.

Can you fix this?

**Comment by schana** [comment]
Most likely cause is battery saving preferences on your phone that prevent communication between the watch and the Fitbit app. The Fitbit app needs to be able to run in the background.

**Comment by Tombella** [comment]
Fitbit has run in background permission.  SPECTRUM face works fine and several others do as wellOn Aug 20, 2021 12:02 PM, Nathaniel Schaaf ***@***.***> wrote:
Most likely cause is battery saving preferences on your phone that prevent communication between the watch and the Fitbit app. The Fitbit app needs to be able to run in the background.

**Comment by schana** [comment]
This is now happening on mine too. Fitbit recently released an update, so I'll have to see what they broke. It's likely the weather updating portion.

**Comment by Tombella** [comment]
It seemed that the weather info disappeared first but I am not sure.It is a great face, lots of dat, but concise Thanks On Aug 20, 2021 2:49 PM, Nathaniel Schaaf ***@***.***> wrote:
This is now happening on mine too. Fitbit recently released an update, so I'll have to see what they broke. It's likely the weather updating portion.

**Comment by schana** [comment]
Yeah. They are now returning an int where they used to return a string. I'll have to update the watch face. Sorry for the inconvenience.

**Comment by Tombella** [comment]
Not to worry.  Please let me know when I should try again.I appreciate the response On Aug 20, 2021 5:39 PM, Nathaniel Schaaf ***@***.***> wrote:
Yeah. They are now returning an int where they used to return a string. I'll have to update the watch face. Sorry for the inconvenience.

**Comment by schana** [comment]
resolved 16747f1ae567390521ad78f8076780978d3625a3

**Comment by schana** [comment]
I submitted the update to fitbit for review.

**Comment by Tombella** [comment]
Thank youOn Aug 21, 2021 11:09 AM, Nathaniel Schaaf ***@***.***> wrote:
I submitted the update to fitbit for review.

**Comment by schana** [comment]
This has been published to the Fitbit gallery.

**Comment by Tombella** [comment]
I just installed the new version.  Works great! Thank youOn Aug 21, 2021 12:38 PM, Tom Bella ***@***.***> wrote:Thank youOn Aug 21, 2021 11:09 AM, Nathaniel Schaaf ***@***.***> wrote:
I submitted the update to fitbit for review.
